#!/usr/bin/env python

import yaml
import sys
import os

import glob

import datetime
from time import gmtime, strftime, sleep

from multiprocessing.dummy import Pool as ThreadPool 
import itertools

from os import listdir
from os.path import isdir, isfile, join

from modules.config_parser import args

def Convert(config, j):
    config = config
    n = j["pos"]
    
    print("Processing job: " + str(n) + "; " + j["infile"] + "; " + j["outfile"])
    
    cmd = config["command"]
    cmd = cmd.replace('%INFILE%', j["infile"])
    cmd = cmd.replace('%OUTFILE%', j["outfile"])
    # print(cmd)
    os.system(cmd)

def dircontents(path, files):
    for f in listdir(path):
        fpath = join(path, f)
        if isfile(fpath) and fpath.endswith('.xml'):
            files.append(fpath)
        elif isdir(fpath):
            dircontents(fpath, files)
    return files
    
config = yaml.safe_load(open(args.config))
print()
print("Config:")
print(config)
print()

jobconfig = config["source2mets"]
print("Job config:")
print(jobconfig)
print()


files = []
files = dircontents(jobconfig["source_directory"], files)

#print(str(len(files)))
#files = files[:10]
#print(files)
#print(str(len(files)))
#print()
# sys.exit(0)

pos = 1
jobs = []
for f in files:
    
    infile = f
    outfile = jobconfig["target_directory"]
    j = {
        "pos": pos,
        "infile": infile,
        "outfile": outfile
    }
    jobs.append(j)
    pos += 1
    
if jobconfig["clean_target_directory"]:
    for f in glob.glob(jobconfig["target_directory"] + "*", recursive=False):
        if isfile(f):
            os.unlink(f)

print()
print("Number of threads: " + str(jobconfig["threads"]))
print("Total number of jobs: " + str(len(jobs)))
print()
st = datetime.datetime.now()
starttime = strftime("%Y-%m-%d %H:%M:%S", gmtime())

# make the Pool of workers
pool = ThreadPool(jobconfig["threads"]) 

# open the urls in their own threads
# and return the results
results = pool.starmap(Convert, zip(itertools.repeat(jobconfig), jobs))

# close the pool and wait for the work to finish 
pool.close() 
pool.join() 

gt = gmtime()
endtime = strftime("%Y-%m-%d %H:%M:%S", gt)
et = datetime.datetime.now()
timedelta = et - st

print()
print()
print ("Task started at: " + starttime)
print ("Task ended at: " + endtime)
print ("Elapsed time: ", str(timedelta))
print()
print()



