

marcxml2bf:
    threads: 5
    command: xsltproc --stringparam baseuri http://id.loc.gov/resources/REPLACE/ --stringparam idsource http://id.loc.gov/vocabulary/organizations/dlcmrc /location/of/xsl/marc2bibframe2.xsl %INFILE% > %OUTFILE% 
    source_directory: /marcxml/source/dir/
    clean_target_directory: true
    target_directory_single_dir: true
    target_directory: /bf/target/dir/
    
source2mets:
    threads: 3
    command: /where/zorba/is/installed/bin/zorba -i --serialize-text -q file:///source/xquery/resources2mets.xqy -e sourceuri:=%INFILE% -e savedir:=%OUTFILE% -e tableORschedule:= -e letter:=
    source_directory: /bf/source/dir/
    clean_target_directory: true
    target_directory_single_dir: true
    target_directory: /mets/target/dir/
    
marc2marcxml:
    threads: 4
    num_records_per_file: 5000
    source_directory: /location/of/marc2709/files/
    tmp_processing_directory: /tmp/
    clean_target_directory: true
    target_directory: /location/of/output/marcxml/files/